### ISSUE TITLE
how do you exactly execute the program?

### ISSUE THREAD

**Issue by yanggatang** [JakeCooper/OnePlusTwoBot#41]

**Comment by ghost** [comment]
open cmd go to the directory you saved it in then do "python <filename>.py" without the quotation marks of course

**Comment by JakeCooper** [comment]
PLEASE do not create multiple issues for a simple question.

If you are unable to run the file from the readme due to an error, please screencap the error for us.

If you are unable to run the file from the readme due to your lack of knowledge of python : http://learnpythonthehardway.org/.

Feel free to reopen this issue if you are going to post a screencap of your error.
