### ISSUE TITLE
GmailExploit2: Request failed. 404

### ISSUE THREAD

**Issue by valentin-13** [JakeCooper/OnePlusTwoBot#48]
Hello,

Whenever I run GmailExploit2, I get these lines and don't get any mails.

![image](https://cloud.githubusercontent.com/assets/13754211/9208395/8ca70464-4073-11e5-9d91-a06bf9114358.png)

Also when I use EmailParser I get this screen

![image](https://cloud.githubusercontent.com/assets/13754211/9208712/20695bca-4074-11e5-90d8-c23f116b8f4a.png)

(Using Python 3.4.3)
Thanks!

**Comment by qwerty123443** [comment]
the 404's don't matter, they succeed after a couple of tries.
as for the not recieving emails; i have noticed that too, i think it's because of the captcha code on the page.
I personally have recieved emails until the 10th of august (yesterday, before the captcha was added).
![1 2 emails](https://cloud.githubusercontent.com/assets/6923387/9210574/563f751e-407d-11e5-9106-53a60db780db.png)

**Comment by valentin-13** [comment]
Thanks for the answer, is probably the captcha indeed.

**Comment by tsitu** [comment]
The 404's happen because emails with more than 2 periods aren't accepted anymore. Since the captcha was added I haven't received any confirmation emails either.

**Comment by qwerty123443** [comment]
well, that's half true, multiple consecutive periods aren't allowed, and things in the format of "l.e.t.t.er@gmail.com" aren't allowed either. On the other hand, it is allowed to do "le.tt.er@gmail.com"

**Comment by tsitu** [comment]
Right, your second example has 2 periods. Anything greater than that is not accepted anymore. This means that a max length Gmail address (30 characters) still has 435 different period placement options.
